### ISSUE TITLE
Missing .gitignore in application template

### ISSUE THREAD

**Issue by Enet4** [stylesuxx/generator-minimal-generator#1]
As I attempted to scaffold a new generator, I got the following error after filling in the base package information:

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/generator-minimal-generator/app/templates/.gitignore'
>     at Error (native)
>     at Object.fs.openSync (fs.js:584:18)
>     at Function.module.exports.sync (/usr/lib/node_modules/generator-minimal-generator/node_modules/read-chunk/index.js:34:14)
>     at copy (/usr/lib/node_modules/generator-minimal-generator/node_modules/yeoman-generator/lib/actions/actions.js:38:27)
>     at module.exports.generators.Base.extend.writing.copyStatics (/usr/lib/node_modules/generator-minimal-generator/app/index.js:101:12)
>     at Object.<anonymous> (/usr/lib/node_modules/generator-minimal-generator/node_modules/yeoman-generator/lib/base.js:426:25)
>     at /usr/lib/node_modules/generator-minimal-generator/node_modules/run-async/index.js:33:25
>     at /usr/lib/node_modules/generator-minimal-generator/node_modules/yeoman-generator/lib/base.js:436:8
>     at processImmediate [as _immediateCallback](timers.js:383:17)

Turns out that the package that was published in the npm contains an ".npmignore" file instead of the expected ".gitignore". As I see that this was fixed in the repository, I would suggest patching the npm package to make sure this change takes place.

**Comment by stylesuxx** [comment]
Thank you for the Bug report. Problem was, that when publishing to npm, the .gitignore was changed to .npmignore. I now renamed the template for gitignore and everything should be good again.

Published new version to NPM.

**Comment by Enet4** [comment]
Ok, that seems to work. Much appreciated!
